global:
  scrape_interval:     30s          # 默认抓取间隔
  evaluation_interval: 30s
  external_labels:
    monitor: 'codelab-monitor'

# 抓取对象的配置
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
 

# 指定Prometheus的存储数据库为InfluxDB
remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus&u=prometheus&p=prometheuspwd"
remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus&u=prometheus&p=prometheuspwd"
 



