# This is a basic workflow to help you get started with Actions

name: upgradeLfs

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run startup.bash
        run: |
           set -e
           echo start
           
           export GIT_SSH_SECRET="${{ secrets.GIT_SSH_SECRET }}"           
           export basePath=$PWD
           
           #复制ssh key
           mkdir -p $basePath/Publish/release
           echo "${GIT_SSH_SECRET}" > $basePath/Publish/release/serset
           chmod 600 $basePath/Publish/release/serset
           
           #推送到github
           docker run -i --rm \
           -v $basePath/Publish/release:/root/release serset/git-client bash -c "
           set -e
           ssh-agent bash -c \"
           ssh-add /root/release/serset
           ssh -T git@github.com -o StrictHostKeyChecking=no
           git config --global user.email 'serset@yeah.com'
           git config --global user.name 'lith'
           mkdir -p /root/code
           git clone git@github.com:serset/release.git /root/code
           
           cd /root/code
           git lfs migrate import --include-ref=master --include='*.zip' -y
           git push -u origin master --force\" "

           echo succeed!

